### ISSUE TITLE
Click target on clipping cards is a little confusing

### ISSUE THREAD

**Issue by goldenmeanie** [javierarce/kindle-to-arena#1]
I can see that it's a trade-off for one click editing of the content of the clipping. But it feels a little weird to have to find the edge of the card to select. 

![click-target](https://user-images.githubusercontent.com/1969/91913041-a10b5700-ec82-11ea-9295-7ee26d0a4911.gif)

**Comment by javierarce** [comment]
Hi, Alex… do you find it weird because it makes difficult to discover the selection behaviour initially? Or because the whole thing is confusing afterwards?

**Comment by goldenmeanie** [comment]
I definitely had trouble discovering the selection behavior at first. It still feels uncomfortable to me personally afterwards. The clickable padding feels like a small target everywhere but the bottom. The need to find empty space to click sort of breaks the card metaphor for me.

I haven't used it enough to see whether the activity is overwhelmingly about selection, or if edits and formatting are a significant task. I can see why you'd want that to be low friction with the sometimes odd scoping that Kindle has for text highlights.

**Comment by javierarce** [comment]
Sorry this took me so much time to fix it. I came up with this solution that I think could solve the problem of discoverability and keep the interface simple and clean. Let me know what you think and thanks for submitting this issue :)

![select](https://user-images.githubusercontent.com/4933/94555959-a5646900-025c-11eb-93c8-d861d6890451.gif)
